export const SAVE_CANDIDATE_FORM_ITEM = 'SAVE_CANDIDATE_FORM_ITEM';

export const REMOVE_CANDIDATE_FORM_ITEM = 'REMOVE_CANDIDATE_FORM_ITEM';

export const SAVE_FORM_ITEM = 'SAVE_FORM_ITEM';
export const SAVE_FORM_ITEM_SUCCESS = 'SAVE_FORM_ITEM_SUCCESS';

export const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';